#!/bin/sh

# install terraform-docs if it is not installed
if ! which terraform-docs > /dev/null; then
   brew install terraform-docs
fi

# Keep module docs up to date in modules directory
for d in modules/*; do
  if terraform-docs markdown table --output-file README.md --output-mode inject "$d/"; then
    git add "./$d/README.md"
  fi
done

# update README.md file with the latest changes to the terraform code over a specific path
# terraform-docs markdown table --output-file README.md --output-mode inject .
# git add README.md

# commit updated README.md files
git commit --no-verify -m "Updated README.md files"