#!/bin/sh

if [ terraform-docs --version | grep -q "command not found" ]
    then brew install terraform-docs
    else terraform-docs --version
fi

terraform-docs markdown table --output-file README.md --output-mode inject .
git add README.md && git commit --no-verify -m "Updated README.md file"