#!/bin/sh

if ! which terraform-docs > /dev/null; then
   brew install terraform-docs
fi

terraform-docs markdown table --output-file README.md --output-mode inject .
git add README.md && git commit --no-verify -m "Updated README.md file"